import Head from "next/head";
import HeroSection from "../components/heroSection";
import SliderContainer from "../components/sliderContainer";
import { useFetch } from "../hooks/useFetch";
import { useEffect, useState } from "react";
import MovieList from "../components/page/index/movieList";
import Loading from "../components/loading";

export default function Home() {
  const [moviesRes, fetchMovies] = useFetch();
  const [tvRes, fetchTv] = useFetch();

  useEffect(() => {
    fetchMovies(
      "https://api.themoviedb.org/3/movie/now_playing/?api_key=d69d21688e524f2e272cb84b6edaf2c6"
    );
    fetchTv(
      "https://api.themoviedb.org/3/movie/tv/airing_today?api_key=d69d21688e524f2e272cb84b6edaf2c6"
    );
  }, []);

  const sliderData = [
    {
      title: "Cinema",
      value: moviesRes?.data?.results,
    },
    {
      title: "Tv",
      value: tvRes?.data?.results,
    },
  ];
  return (
    <div>
      <Head>
        <title>Kia Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-800 ">
        <HeroSection />
        <div className="transform -translate-y-32 bg-gray-800 ">
          {moviesRes.loading ? (
            <Loading />
          ) : (
            <SliderContainer title={"New Releases"} data={sliderData} />
          )}
        </div>
        <MovieList />
      </main>
    </div>
  );
}
